SUPABASE_URL="https://oujauosggttdaoyxzyyw.supabase.co"
ARCORE_KEY = "AIzaSyDfXi-nbQ_qBWXTqKa_3MX7lAV_UbUxQxg"
SUPABASE_KEY1="sb_publishable_VtBQk6n1_yjS3WbO2lbOGA_9RyAXQ2M"

APPWRITE_PROJECT_ID = 69a2ed550010437aa35e
APPWRITE_PROJECT_NAME = "StellAR"
APPWRITE_PUBLIC_ENDPOINT ="https://sgp.cloud.appwrite.io/v1"

SUPABASE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91amF1b3NnZ3R0ZGFveXh6eXl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU2OTY2NjEsImV4cCI6MjA4MTI3MjY2MX0.fFpTHPJYvrCNkvSVbJAUYqYittp89rtSAsatDkHw6lA"